--- 
version: 2.1
orbs:
   snyk: snyk/snyk@1.1.2
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk-browsers"
    steps: 
      - checkout
      - snyk/scan
      -
          run: 
            command: | 
                # install DumpsterDiver here
                echo "installing pip and running DumpsterDiver"
                sudo apt-get install pip
                git clone https://github.com/securing/DumpsterDiver.git
                cd DumpsterDiver
                pip install -r requirements.txt
                python3 DumpsterDiver.py -p /home/circleci/spring-rest-helloworld --min-key 40 --max-key 40 --entropy 4.3
            name: "dumpster diver"
            
      - setup_remote_docker
      - 
        restore_cache: 
          key: "spring-rest-helloworld-{{ checksum \"pom.xml\" }}"
      - 
        run: "mvn dependency:go-offline"
      - 
        save_cache: 
          key: "circleci-demo-java-spring-{{ checksum \"pom.xml\" }}"
          paths: 
            - ~/.m2
      - 
        run: "mvn package"
      - 
        store_test_results: 
          path: target/surefire-reports
      - 
        store_artifacts: 
          path: target/spring-rest-helloworld-0.0.1-SNAPSHOT.war
      - 
        run: 
          command: "if mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec | grep -q \"SNAPSHOT\"; then mvn versions:set -DremoveSnapshot; fi;\n\
              echo $(mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive exec:exec)-$(echo $CIRCLE_SHA1 | cut -c -7)-$CIRCLE_BUILD_NUM > tempvers.txt\n\
              mvn versions:set -DnewVersion=$(cat tempvers.txt) \n"
          name: "remove snapshot version"
      - 
        run: 
          command: |
              cp target/*.war docker/app/
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker build --no-cache -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(cat tempvers.txt) docker
              docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(cat tempvers.txt)
          name: "Build application Docker image"
    working_directory: ~/spring-rest-helloworld
    
    -
        run: 
          command: | 
              sudo apt-get install wget apt-transport-https gnupg lsb-release
              wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
              echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
              sudo apt-get update
              sudo apt-get install trivy
              trivy image $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(cat tempvers.txt)
          name: "trivy"
